### ISSUE TITLE
Slow Combat, logging out.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#646] opened 2016-08-21 18:41 UTC
When in combat, some areas have terrible spawn rates. With bad enough spawn rate, you will be logged out from idleness. 

http://pastebin.com/zuhUtQi6

**Comment by drboldwin** [comment] 2016-08-21 22:51
this could be avoided by running ;afk as well as provide you with added security.

**Comment by rpherbig** [comment] 2016-08-22 12:38
This is a duplicate of #312

**Closed by rpherbig** 2016-08-22 12:38 UTC
