### ISSUE TITLE
combat-trainer doesn't know what to do with a full gem pouch

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#353] opened 2016-04-16 04:35 UTC
Gems that can't be stowed could be dropped or have an overflow container(s) setting in the setup.yaml file that combat trainer would STORE GEMS IN <container> as a new default.

gem_container: pouch      combat-trainer could set this default when it starts
gem_overflow_bags:
- haversack
- rucksack

[combat-trainer]>tie my crossbow to braided toolstrap
You attach a forester's crossbow to your braided toolstrap.
>
[combat-trainer]>get my femur-blasting.maul
You get a femur-blasting maul from inside your duffel bag.
>
[combat-trainer]>stance set 100 82 0
Setting your Evasion stance to 100%, your Parry stance to 82%, and your Shield stance to 0%.  You have 0 stance points left.
>
[combat-trainer]>loot
You search the swamp troll.
Lodged into it was a crossbow bolt, a crossbow bolt, and a crossbow bolt.
The troll was carrying a tiny moss-green chrysoprase and a huge nickel nugget!
>
The troll decomposes.  Not that it looks much different that way.
>
[combat-trainer]>stow bolt
You pick up a crossbow bolt.
You put your bolt in your painted quiver.
>
[combat-trainer]>stow bolt
You pick up a crossbow bolt.
You put your bolt in your painted quiver.
>
[combat-trainer]>stow bolt
You pick up a crossbow bolt.
You put your bolt in your painted quiver.
>
[combat-trainer]>stow bolt
You pick up a crossbow bolt.
You put your bolt in your painted quiver.
[combat-trainer]>stow chryso
>
You pick up a tiny moss-green chrysoprase.
You've already got a wealth of gems in there!  You'd better tie it up before putting more gems inside.
>
The swamp troll moves into a position to parry.
>
A swamp troll gestures at you.
A swamp troll bellows a word of power.
>
[combat-trainer]>jab
You turn to face a swamp troll.
You need two hands to wield this weapon!
>
[combat-trainer]>jab
You need two hands to wield this weapon!

**Comment by rpherbig** [comment] 2016-04-19 00:51
This is a duplicate of #203. Still a good idea though :)

**Closed by rpherbig** 2016-04-19 00:51 UTC
Labels: combat-trainer
