### ISSUE TITLE
Hunting-buddy- After:  Applies to last YAML file in group if subsequent identical hunting areas are used.

### ISSUE THREAD

**Issue by intangibles** [rpherbig/dr-scripts#1488] opened 2017-03-17 21:25 UTC
I'm running into an issue where After: is not triggering via hunting-buddy.

I think I've narrowed the issue down to this line
`line 70   args.each_with_index { |arg, index| hunt(arg, duration ? duration[index] : nil, stop_on_skills ? stop_on_skills[index] : nil) }`

I added in echos to see if i could track down the issue. If you examine the logs, you'll notice there is no echos between the first YAML and the ending YAML, so the script is not touching any of the lines related to after: until the very end.

I tested the YAML script using:
;en DRC.wait_for_script_to_complete('hunting-buddy', ['stealth'])"
And the AFTER: fired correctly. 

My hunch is that because I have 4 YAMLs in the same area, it's not properly rechecking the before: & afters:.   I'm also thinking that maybe an AFTER: on my first YAML, setup.yaml might trigger correctly.
 **See second comment.  Confirmed that AFTER on first YAML applies to last YAML** 

```
 args = info['args']
      echo args
      before_actions = info['before']
     echo before_actions
      after_actions = info['after']
      echo after_actions
      duration = info[:duration]
      stop_on_skills = info['stop_on']

      # Execute scripts to run before the hunt
      execute_actions(before_actions)

      if all_skills_at_cap?(stop_on_skills)
        # Execute scripts to run after the hunt
        execute_actions(after_actions)
        next
      end
      next unless find_hunting_room?(info[:zone])

      args.each_with_index { |arg, index| hunt(arg, duration ? duration[index] : nil, stop_on_skills ? stop_on_skills[index] : nil) }

      echo after_actions
      wait_for_script_to_complete('bescort', @exit) if @exit
      release_cyclics

      # Execute scripts to run after the hunt
     echo after_actions
      execute_actions(after_actions)
    end
    walk_to(@settings.safe_room)
    EquipmentManager.new.wear_equipment_set?('standard')
  end
```

Here is the log of the echos

>  4428: [hunting-buddy: [["d0", "setup"], ["tm"], ["stealth"]]]
> 	Line 4429: [hunting-buddy: ["go2 6169", "startCyclic research", "pick pets 100", "pick", "collect rock", "1appraisal", "Athletics", "go2 6169", "1first-aid", "startCyclic exit", "buff combat"]]
> 	Line 4430: [hunting-buddy: ]
> 	Line 4431: [hunting-buddy: ***STATUS*** EXECUTE go2 6169]
> 	Line 4437: [hunting-buddy: ***STATUS*** EXECUTE startCyclic research]
> 	Line 4512: [hunting-buddy: ***STATUS*** EXECUTE pick pets 100]
> 	Line 4645: [hunting-buddy: ***STATUS*** EXECUTE pick]
> 	Line 5272: [hunting-buddy: ***STATUS*** EXECUTE collect rock]
> 	Line 5808: [hunting-buddy: ***STATUS*** EXECUTE 1appraisal]
> 	Line 6312: [hunting-buddy: ***STATUS*** EXECUTE Athletics]
> 	Line 9649: [hunting-buddy: ***STATUS*** EXECUTE go2 6169]
> 	Line 9993: [hunting-buddy: ***STATUS*** EXECUTE 1first-aid]
> 	Line 10222: [hunting-buddy: ***STATUS*** EXECUTE startCyclic exit]
> 	Line 10229: [hunting-buddy: ***STATUS*** EXECUTE buff combat]
> 	Line 11038: [hunting-buddy: ***STATUS*** beginning hunt '["d0", "setup"]' for '15' minutes]
> 	Line 11057: [hunting-buddy: ***STATUS*** 15 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 11290: [hunting-buddy: ***STATUS*** 14 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 11510: [hunting-buddy: ***STATUS*** 13 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 11714: [hunting-buddy: ***STATUS*** 12 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 11948: [hunting-buddy: ***STATUS*** 11 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 12160: [hunting-buddy: ***STATUS*** 10 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 12383: [hunting-buddy: ***STATUS*** 9 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 12592: [hunting-buddy: ***STATUS*** 8 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 12811: [hunting-buddy: ***STATUS*** 7 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 13039: [hunting-buddy: ***STATUS*** 6 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 13283: [hunting-buddy: ***STATUS*** 5 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 13545: [hunting-buddy: ***STATUS*** 4 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 13762: [hunting-buddy: ***STATUS*** 3 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 13996: [hunting-buddy: ***STATUS*** 2 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 14198: [hunting-buddy: ***STATUS*** 1 minutes of hunting remaining or waiting on Light Thrown]
> 	Line 14441: [hunting-buddy: ***STATUS*** stopping due to time]
> 	Line 16129: [hunting-buddy]>retreat
> 	Line 16131: [hunting-buddy: ***STATUS*** beginning hunt '["tm"]' for '10' minutes]
> 	Line 16159: [hunting-buddy: ***STATUS*** 10 minutes of hunting remaining or waiting on Sorcery, Targeted Magic]
> 	Line 16358: [hunting-buddy: ***STATUS*** 9 minutes of hunting remaining or waiting on Sorcery, Targeted Magic]
> 	Line 16507: [hunting-buddy: ***STATUS*** 8 minutes of hunting remaining or waiting on Sorcery, Targeted Magic]
> 	Line 16705: [hunting-buddy: ***STATUS*** 7 minutes of hunting remaining or waiting on Sorcery, Targeted Magic]
> 	Line 16898: [hunting-buddy: ***STATUS*** 6 minutes of hunting remaining or waiting on Sorcery, Targeted Magic]
> 	Line 17065: [hunting-buddy: ***STATUS*** 5 minutes of hunting remaining or waiting on Sorcery, Targeted Magic]
> 	Line 17232: [hunting-buddy: ***STATUS*** 4 minutes of hunting remaining or waiting on Sorcery, Targeted Magic]
> 	Line 17415: [hunting-buddy: ***STATUS*** 3 minutes of hunting remaining or waiting on Sorcery, Targeted Magic]
> 	Line 17578: [hunting-buddy: ***STATUS*** 2 minutes of hunting remaining or waiting on Sorcery, Targeted Magic]
> 	Line 17751: [hunting-buddy: ***STATUS*** 1 minutes of hunting remaining or waiting on Sorcery, Targeted Magic]
> 	Line 17902: [hunting-buddy: ***STATUS*** stopping due to time]
> 	Line 17980: [hunting-buddy]>retreat
> 	Line 17982: [hunting-buddy: ***STATUS*** beginning hunt '["stealth"]' for '10' minutes]
> 	Line 18016: [hunting-buddy: ***STATUS*** 10 minutes of hunting remaining or waiting on Stealth]
> 	Line 18140: [hunting-buddy: ***STATUS*** 9 minutes of hunting remaining or waiting on Stealth]
> 	Line 18255: [hunting-buddy: ***STATUS*** 8 minutes of hunting remaining or waiting on Stealth]
> 	Line 18326: [hunting-buddy: ***STATUS*** 7 minutes of hunting remaining or waiting on Stealth]
> 	Line 18377: [hunting-buddy: ***STATUS*** 6 minutes of hunting remaining or waiting on Stealth]
> 	Line 18438: [hunting-buddy: ***STATUS*** 5 minutes of hunting remaining or waiting on Stealth]
> 	Line 18487: [hunting-buddy: ***STATUS*** 4 minutes of hunting remaining or waiting on Stealth]
> 	Line 18533: [hunting-buddy: ***STATUS*** 3 minutes of hunting remaining or waiting on Stealth]
> 	Line 18599: [hunting-buddy: ***STATUS*** 2 minutes of hunting remaining or waiting on Stealth]
> 	Line 18645: [hunting-buddy: ***STATUS*** 1 minutes of hunting remaining or waiting on Stealth]
> 	Line 18690: [hunting-buddy: ***STATUS*** stopping due to time]
> 	Line 18694: [hunting-buddy: ]
> 	Line 18717: [hunting-buddy: ]

These are the echos related to line 18694 above, and directly around the bescort echos in the echo code.

> [hunting-buddy: ***STATUS*** stopping due to time]
> [combat-trainer]>stow my throwing.axe
> You easily strap your throwing axe to a shimmering faeweave baldric with cambrinth buckles.
> --- Lich: combat-trainer has exited.
> [hunting-buddy: ]
> --- Lich: bescort active.
> [bescort]>west
> You feel confident you are heading in the right direction.
> You go west.
> [Wilderness]
> Scraggly trees grow close together, poking up through the wild, arching brush.  Toward the southeast, the woods and undergrowth thicken into a dark, tangled mass, making travel confusing at best.  
> Obvious paths: east, south, northwest.
> Blazed trails:  none.
> [bescort]>northwest
> You feel confident you are heading in the right direction.
> You go northwest.
> [Wilderness, Dry Streambed]
> A lively brook once bubbled through the narrow gully, but time and drought have left only this cracked streambed as a reminder.  A few straggling weeds poke up through flakes of rock-hard dried mud.  Several courses of ancient stone line both banks, showing the hand of one who wished to control the wanderings of nature.  You also see a giant black leucro, a weathered signpost and an animal trail.
> Obvious paths: none.
> --- Lich: bescort has exited.
> Manifest Force  (4 roisaen)
> Obfuscation  (11 roisaen)
> Ivory Mask  (10 roisaen)
> Philosopher's Preservation  (9 roisaen)
> Kura-Silma  (10 roisaen)
> The black leucro begins to advance on you!
> The black leucro is still a distance away from you and is closing steadily.
> [hunting-buddy: ]
> --- Lich: go2 active.
> [go2: ETA: 0:00:25 (111 rooms to move through)]
> [go2]>search
> You search around for a moment.
> 

```
YAML File
---
hunting_info:
- :zone: leucro1
  args:
  - stealth
  :duration: 10
  after:
  - necroHeal
  - startCyclic
  stop_on:
  - Stealth

training_abilities:
  Hunt: 80
  Perc: 60
use_stealth_attacks: true

dance_threshold: 0
dance_skill: Small Edged
Small Edged: feint
weapon_training:
  Small Edged: throwing axe
  Polearms: light spear

aim_fillers:
  Bow:
  - bob
  - bob
  - bob

offensive_spells:
combat_spell_training:
offensive_spell_cycle:
cycle_armors:

thanatology:
  ritual_type: harvest
  heal: false
necromancer_healing:
  Consume Flesh:
    abbrev: CF
    mana: 15
    cambrinth:
    - 5

gear_sets:
  standard:
  - mail balaclava
  - mail lorica
  - mail gloves
  #- mail greaves
  #- mail vambraces
  - diamond-hide shield
  - parry stick
  - shalswar handwraps

```

**Comment by intangibles** [comment] 2017-03-17 22:16
Just confirmed that if I run an AFTER:  in the first YAML in my series of back files, it activates after the LAST YAML has finished.

before_actions = info['before']
echo before_actions
Line 7777: [hunting-buddy: ["go2 6169", "startCyclic research", "pick pets 100", "pick", "collect rock", "1appraisal", "Athletics", "go2 6169", "1first-aid", "startCyclic exit", "buff combat"]]

after_actions = info['after']
echo after_actions
Line 7778: [hunting-buddy: ["necroHeal", "startCyclic"]]

**Comment by intangibles** [comment] 2017-03-17 22:51
Logs confirming.

Ignore the script error!

> The black leucro is still a distance away from you and is closing steadily.
> > 
> You are already as far away as you can get!
> > 
> [hunting-buddy: ["necroHeal", "startCyclic"]]
> 
> --- Lich: bescort active.
> 
>  
> --- Lich: bescort has exited.
> 
> [hunting-buddy: ["necroHeal", "startCyclic"]]
> 
> [hunting-buddy: ***STATUS*** EXECUTE necroHeal]
> 
> --- Lich: necroHeal active.
> 
> [necroHeal]>health
> 
> Your body feels somewhat battered.
> Your spirit feels full of life.
> You are slightly fatigued.
> You have a bruised head compounded by cuts and bruises about the head, minor swelling and bruising around the right arm compounded by cuts and bruises about the right arm, some tiny scratches to the left arm, some minor abrasions to the right leg, minor swelling and bruising around the left leg compounded by cuts and bruises about the left leg, some minor abrasions to the chest, some minor abrasions to the abdomen.
> 
> > 
> --- Lich: error: private method `kill_script' called for Scripting::DRC:Module
> 	necroHeal:39:in `script'
> 	lich.rbw:2545:in `eval'
> 
> --- Lich: necroHeal has exited.
> 
> [hunting-buddy: ***STATUS*** EXECUTE startCyclic]
> 
> --- Lich: startCyclic active.
> 
> [startCyclic]>release all
> 
>

**Comment by adamgoerdt** [comment] 2017-03-18 02:03
Did a bit of testing, and the issue is only present if two subsequents hunts use the same zone.  Looking through the hunting-buddy code I can't see any way to resolve this without removing the feature that combines duplicate zones (the `format_hunting_info` method)

**Comment by rpherbig** [comment] 2017-06-26 13:46
@rcuhljr Did your recent change to hunting behave affect this?

**Comment by rcuhljr** [comment] 2017-06-26 14:24
Unlikely. There's really not a good fix for this currently and the need was low.

**Closed by rcuhljr** 2017-06-26 14:24 UTC
