### ISSUE TITLE
go2 Therenborough to Riverhaven

### ISSUE THREAD

**Issue by cfrisby77** [rpherbig/dr-scripts#5104] opened 2021-07-23 21:13 UTC
Go2 will take the rope south but not check perception and gets stuck on the handhold in Mistwood.

On this character, it takes the Ferry / Barge North. 

I didn't get that far but I have a feeling I would have gotten stuck in the river if was able to get past the climbing part.
This is a new character
Perception: 106
Athletics: 85

> 
> [go2]>search out
> You poke around, closely examining a rocky outcropping, but don't find anything of interest.
> >
> [go2]>climb hand
> What were you referring to?
> >
> [go2: move: failed]
> [go2]>climb hand
> What were you referring to?
> >
> [go2: move: failed]
> [go2: restarting script...]
> >
> [go2: ETA: 0:00:35 (165 rooms to move through)]
> [go2]>search out
> You poke around, closely examining a rocky outcropping, but don't find anything of interest.
>

**Comment by wstampley** [comment] 2021-08-02 01:09
Yep. About once a month, more during guild-fest, someone gets stuck in that spot.

**Comment by MahtraDR** [comment] 2022-01-06 01:16
@BinuDR Did you ever end up looking into this one? 

@cfrisby77 I don't know that spot, can you give me a room number, or steps to reproduce?

**Comment by MahtraDR** [comment] 2022-01-06 01:31
@Hiinky I spoke with Binu about this on Discord, and he suggested we might need a map change here. Could you look into this one?

**Comment by MahtraDR** [comment] 2022-01-06 01:34
from Binu on Discord just now ```Binu — Today at 2:33 PM
I'll have to find the room number, but basically the timeto for that room needs editing to have a skill check (or a higher skillcheck if it already has one)
```

**Comment by Hiinky** [comment] 2022-01-06 01:39
I'm aware of the spot but i don't believe we know the exact perception check and it would require a map lock.  Unfortunately it is not a priority edit to risk a lock until we have more information and multiple "locking" edits to do at one time.  It is also a very small window in which folks are effected.

**Comment by MahtraDR** [comment] 2022-01-06 01:45
@Hiinky Leave this open till then, or can we "queue" the change so it'll go in on your next edit?

**Comment by Hiinky** [comment] 2022-01-06 01:48
it's already on my list.

**Comment by MahtraDR** [comment] 2022-01-07 02:10
@rpherbig since this isn't something we can fix in this repo, as it's a mapdb entry, and Kali's got it in her list already when she next has to lock the map... let's close this.

**Closed** 2022-01-07 02:20 UTC
