### ISSUE TITLE
Combat-Trainer Stuck when trying to swap without hand

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#3338] opened 2018-12-30 11:48 UTC
Lost a hand due to sorcery, cant swap weapons. This loops forever until hunting buddy kills the hunt.
```
[combat-trainer: *** No match was found after 15 seconds, dumping info]                                                                                                                                                        
[combat-trainer: messages seen length: 19]                                                                                                                                                                                     
[combat-trainer: message: [You're bruised, solidly balanced and opponent has slight advantage.]]                                                                                                                               
[combat-trainer: message: * As if effort and skill were a bad thing, a zombie head-splitter moans hauntingly and stomps at you.  You block with a small puffy-white shield sealed with protective wax.  ]                      
[combat-trainer: message: The head-splitter wanders about in confusion, scratching its head thoughtfully.]                                                                                                                     
[combat-trainer: message: [You're bruised, solidly balanced and in excellent position.]]                                                                                                                                       
[combat-trainer: message: * Looking as if this were a bad idea, a zombie head-splitter charges at you.  You dodge.  ]                                                                                                          
[combat-trainer: message: [You're bruised, solidly balanced and in good position.]]                                                                                                                                            
[combat-trainer: message: * In a weak and directionless display of aggression, a zombie head-splitter swings at you.  You dodge, twisting easily away from the blow.  ]                                                        
[combat-trainer: message: [You're bruised, solidly balanced and have slight advantage.]]                                                                                                                                       
[combat-trainer: message: * With pathetic timing, a zombie head-splitter looms menacingly and swings at you.  You block with a small puffy-white shield sealed with protective wax.  ]                                         
[combat-trainer: message: [You're bruised, solidly balanced and in better position.]]                                                                                                                                          
[combat-trainer: message: * Awkwardly, a zombie head-splitter charges at you.  You block with a small puffy-white shield sealed with protective wax.  ]                                                                        
[combat-trainer: message:  * Holy Light Sumatai joins the adventure.]                                                                                                                                                          
[combat-trainer: message: [You're bruised, solidly balanced and in excellent position.]]                                                                                                                                       
[combat-trainer: message: * Apparently without direction or thought, a zombie head-splitter charges at you.  You dodge, stepping aside with ease.  ]                                                                           
[combat-trainer: message: [You're bruised, solidly balanced and in better position.]]                                                                                                                                          
[combat-trainer: message: * In a weak and directionless display of aggression, a zombie head-splitter swings at you.  You block solidly with a small puffy-white shield sealed with protective wax.  ]                         
[combat-trainer: message: [You're bruised, solidly balanced and in better position.]]                                                                                                                                          
[combat-trainer: message: * Awkwardly, a zombie head-splitter charges at you.  You dodge, moving cleanly out of the way.  ]                                                                                                    
[combat-trainer: message: Your right hand is too injured to do that.]                                                                                                                                                          
[combat-trainer: checked against [/ heavy blunt /i, /\bmace\b.*(heavy edged|two-handed edged|heavy blunt|two-handed blunt|light edged|medium edged|light blunt|medium blunt|light thrown|short staff|quarter staff|halberd)/i]]
[combat-trainer: for command swap my mace]                                                                                                                                                                                     
```

**Comment by jandersson** [comment] 2018-12-30 12:00
On a related note. the stop_hunting_if_bleeding flag doesn't seem to be used when I have equipmanager return on the 'hand too injured message'

**Comment by Sarvatt** [comment] 2018-12-31 02:46
this happens with severe paralysis too https://github.com/rpherbig/dr-scripts/issues/2952

**Comment by drgabellia** [comment] 2019-07-05 16:50
On a related note....you can see by the snippit below that Hunting buddy stopped due to bleeding, but then...I just stood there as it tried to wield/load my slingshot

[hunting-buddy: ***STATUS*** stopping due to bleeding]  <----

[combat-trainer]>wield my finivire.slingshot

Your right hand is too injured to draw the finivire slingshot!


Deleted misc creature scroll for ease in reading this.....then this happens:

[combat-trainer]>load

Your body feels slightly battered.
Your spirit feels full of life.
You have some tiny scratches to the right arm, some minor abrasions to the left arm, an ugly stump for a right hand.

Bleeding
            Area       Rate              
-----------------------------------------
      right hand       very bad

What weapon are you trying to load?

[tendme]>tend my right hand

Your right hand is too injured for you to do that.

So....I stand there repeating the above until I autolog.

Hope this is a simple fix!

**Comment by rpherbig** [comment] 2019-09-18 11:40
Duplicate of #3640

**Closed by rpherbig** 2019-09-18 11:40 UTC
