### ISSUE TITLE
combat-trainer does nothing if waiting for more mana to infuse om

### ISSUE THREAD

**Issue by Donntae** [rpherbig/dr-scripts#6314] opened 2023-01-20 01:25 UTC
In cases where mana is below the casting threshold, combat-trainer does nothing while waiting to infuse Orsel Meraud.

Requesting a fix that would allow combat-trainer to dance or use physical attacks while waiting for mana to hit the casting threshold to infuse om.

**Comment by MahtraDR** [comment] 2023-01-24 05:36
Could you please show a log of this happening?

Thanks!

**Comment by MahtraDR** [comment] 2023-01-24 11:06
Poking into this a bit. This isn't a combat trainer bug. It's a common-arcana issue. Combat-trainer just calls common-arcana.

If we don't wait for mana, we might never get the mana to infuse OM, since something else might use that mana in the mean time. The check is to sit and wait till mana is above 40.  I'm hesitant to change this behaviour. What's the problem this is causing?

**Comment by vtcifer** [comment] 2023-01-27 21:15
Yeah, this is one of those imo, Working as intended.  Keeping OM up for the most part imo should be highest priority otherwise a _host_ of other buffs are likely to drop off, which you'll then also need to recast, making the mana issues even worse.  

Better mana management on the player part is likely the best solution, but more info would be needed to confirm.

**Comment by mikejcook** [comment] 2023-01-31 04:55
I don't have a cleric with OM, but maybe something like the below would help? Short-circuit any magic actions until OM is able to infuse. It should then fill in the gap with other basic actions until the mana is up above 40. I don't really have a horse in this race, but I could see how it would be annoying if the character is standing around doing nothing waiting for mana. Sometimes you get the short end of the stick on mana rooms, and there's not much you can do about that.

```
    check_osrel(game_state)
    return false if @osrel_need_mana
```

```
  def check_osrel(game_state)
    return if game_state.casting
    return unless @osrel_amount && DRSpells.active_spells['Osrel Meraud']
    return unless Time.now - @osrel_timer > 300

    if DRStats.mana <= 40
      @osrel_need_mana = true
      return
    end

    @osrel_timer = Time.now
    infuse_om(!@osrel_no_harness, @osrel_amount)
    @osrel_need_mana = false
  end
```

**Comment by MahtraDR** [comment] 2023-01-31 09:20
> check_osrel

That's a neat idea. If you're keen to code id, and we get a tester, that looks like a workable solution.

**Comment by mikejcook** [comment] 2023-01-31 16:24
Will do.

**Comment by mikejcook** [comment] 2023-02-01 22:28
@Donntae Would you be able to test a possible fix for this?

Here's a link to the raw file you can place in your custom scripts folder. Please run combat-trainer with the debug argument, and when your mana is under 40, you should see messaging about skipping spells until your mana is over 40, and it should perform other activities, such as attacking and so forth.

https://github.com/rpherbig/dr-scripts/blob/7f9b6671aacfca8d5fbad92224639c8c04c05a2b/combat-trainer.lic

**Comment by Donntae** [comment] 2023-02-02 00:32
I'll test and post the results. Thanks for working the issue.

**Comment by Donntae** [comment] 2023-02-02 01:44
Log: https://pastebin.com/XDyWcj4a

It seems like the "Setting @osrel_need_mana to true until mana over 40. Current mana: 26" messaging comes up even if om is over the threshold for need to be recharged. When combat-trainer starts to harn and infuse om but is not able to reach 100%, it still pauses when mana drops below the casting threshold, taking no actions until mana returns to the threshold and it can infuse om to 100%.

**Comment by mikejcook** [comment] 2023-02-02 04:18
@Donntae I've made a couple changes. The first issue was easy to correct, so with these changes, that should be all set.

The second is a little more complicated, but I have an idea to address it. Basically, by the time we start infusing, we're out of combat-trainer's hands, and I don't really want to change the core logic that's infusing OM. However, a middle ground is that I've added a setting you can set in your yaml that controls how much mana you need to have before it'll let you start doing your infusions.

So, with these changes, if your OM is under 90, it'll check your mana level against this new setting (default is 40%). Once over the threshold, it'll go ahead and start the infusion process. So, in your case, you could set your threshold to something higher so that once you get into infusing, it should have plenty of mana to make it happen. For example, you might set it to something like 50 - it might take some trial and error to get the level right.

To test this out, you will need an additional file, base.yaml, which I have linked to below. You will need to put this in your profiles directory in your main scripts folder. You will also need a new combat-trainer, linked below, overwriting the one you copied earlier.

This is my profiles folder: C:\Ruby4Lich5\Lich5\scripts\profiles

And then finally, you will need to put the new osrel_mana_threshold setting in your character's yaml.

osrel_mana_threshold: 50

https://raw.githubusercontent.com/rpherbig/dr-scripts/1885379c2e52228afbe0e49c4e35ad279e57c3b2/combat-trainer.lic
https://raw.githubusercontent.com/rpherbig/dr-scripts/1885379c2e52228afbe0e49c4e35ad279e57c3b2/profiles/base.yaml

**Comment by Donntae** [comment] 2023-02-03 01:53
This version appears to be working perfectly. I'll test a bit longer and post a log.

**Comment by Donntae** [comment] 2023-02-05 16:21
Log: https://pastebin.com/Q7TEvwRA

After a few days of testing, combat-trainer seems to be running flawlessly. When om drops below 90, it pauses spell casting until it reaches the om threshold, while continuing to do non-magical actions. Once om's been refreshed, it continues with spell casting as normal.

The original issues is one that is likely to occur in circumstances where only low mana rooms are available for hunting, or in leucro, geni and other bescort hunting zones that ignore the mana threshold. Many of these bescort hunting zones are within the rank range when f2p clerics first acquire om. This fix solves the issue.

@mikejcook Thanks for working on this.

**Comment by mikejcook** [comment] 2023-02-07 04:48
I've marked the pull request as ready for review. @MahtraDR https://github.com/rpherbig/dr-scripts/pull/6360

**Comment by MahtraDR** [comment] 2023-02-07 04:55
> I've marked the pull request as ready for review. @MahtraDR #6360

Merging now. Note I'm out of town this week, so things are even slower than usual. :)

**Closed** 2023-02-07 04:55 UTC
Labels: Script: combat-trainer, Script: common-arcana
