### ISSUE TITLE
Issue with steal attempting to bin in Shard, stuck in undershard attempting to exit the room using wrong command

### ISSUE THREAD

**Issue by blackheart217** [rpherbig/dr-scripts#3841] opened 2019-09-06 17:52 UTC
The issue only seems to occur when trying to enter undershard from certain locations.  Khri sight is put up, and when it gets to the problematic room it attempts to go "out" and also "go open", which leads to go2 failures.

Here is a pastebin, including the pathing lead-in to the issue.  

https://pastebin.com/3kK9dtGc

At some point in this log I manually type "go gap" which is the correct exit from that room to get to the guild entrance, and go2 and steal take over again to enter and begin binning.  Binu may have some additional insight as he looked into it a little while back.

The log i pasted is using genie+lich, but I also experience the issue with SF.

**Comment by MahtraDR** [comment] 2022-02-09 00:28
This looks to be a map issue, which I can't reproduce today. Closing. Will look at a new issue as fresh if one comes in.

**Closed by MahtraDR** 2022-02-09 00:28 UTC
Labels: Script: steal, Guild: Thief
