### ISSUE TITLE
Sorcery Backlash Logic for Arm/Hands blown off and paralysis

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#1664] opened 2017-05-24 21:31 UTC
Two parter - 

Those of us who train sorcery sometimes end up with missing limbs or full paralysis. This can cause combat-trainer to hang, either trying to bloody stump punch (hereafter called BSP) in the event of a right hand (or offhand!) being blown off, leaving behind a weapon, OR, due to full paralysis bork up the rest of our routines. Two suggested additions to base-spells on backlash that results in missing arms/hands or paralysis-

First is for non-necros -
Stow whatever weapon was being used (it'll be on the ground or in the non-burned off hand). End current hunt (do not wait for critter death). Head to safe room and head to autopuff. Restart hunting-buddy at the yaml stopped on.

Second is for necros - 
Pause hunting-buddy. Stow whatever weapon was being used (it'll be on the ground or in the non-burned off hand). PREP DEVOUR at whatever it is set to in the yaml for Necro-healing. GET MATERIAL (if no material is available, this may require a log off, or engagement of a different yaml specifically for healing on lower critters). Cast. Check for bleeding. If still bleeding, repeat devour cast. If no longer bleeding, get whatever weapon was being used, unpause hunting-buddy.

In both cases, this will prevent BSP until the end of the hunt duration and leaving behind of a weapon. In the case of Necros, this, potentially coupled with a bleeding check, could be a good way to make self-healing more fluid during hunts. Currently the logic for self-healing is fantastic, though it relies on the presence of corpses, which can be tricky to generate via BSP. 

@jandersson 
@intangibles

**Comment by intangibles** [comment] 2017-05-24 21:45
Writing code to stow items that drop from a sorcery backlash is essentially a no-go.  Because sorcery can burn both hands, you can(and will) end up in a situation where you simply cannot pick-up the dropped item and it's lost anyways.

If players insist on holding items when casting sorcery, then the only real 100% safe way is to build empty_hands into the cast methods when sorcery is being cast.  We would probably need to add a sorcery flag to spell YAMLS.

I agree with your comments for necromancers (besides the item dropping).  There is serious issues with trying to kill creatures with missing hands and blown nerves.  Have we confirmed that you can grab fetish materials with two missing hands?

For the consume logic I'd like to see a couple switches added. 
- Missing right hand? Use off-hand weapon
- Missing both hands? Use-TM.
- Missing left hand? Use main-hand weapon.
- Damaged nerves? Rashes? etc.  Use low prep consume or devour.

**Comment by izawwlgood** [comment] 2017-05-25 03:08
True, I didnt consider the possibility of both hands being blown off. In that case, no, you cannot use material. However, given the rarity of that backlash, I think that could simply be a final contingency on the rest of what I presented.

I use Sorcery casting as part of my normal routines, and thus, yes, have held weapons. So far it hasnt been an issue, due to the low backlash rates, but I have on rare occasion had to manually stop things and heal up. I could set up sorcery using Targeted Magic under weaponskills, sure, but Im not sure its currently set up to check Sorcery, instead of Targeted Magic.

Given that I use Sorcery in all yamls, I would prefer to not rely on weapons to kill a critter in the event of a backlash. I would very much prefer that a backlash of this sort uses material first, to fix the issue.

**Comment by BastionWT** [comment] 2017-05-25 13:37
Most people I know that do combat sorcery do so with weapons in hands, with Sorcery as the check for the spell already:
```
- skill: Sorcery
  name: Harawep's Bonds
  abbrev: hb
  mana: 3
  cambrinth:
  - 9
  cast_only_to_train: true
  harmless: true
```

**Comment by wscherer420** [comment] 2017-07-08 21:48
if hands are blown off due to a sorcery backlash, and you drop the weapon, and exit will the weapon be on the ground when you log back in?  Similarly to how a lobbed weapon will remain on the ground until you log back in?  If so, my opinion is, in order to save the weapon, that if both arms are blown off that the game exits you.

**Comment by rpherbig** [comment] 2019-09-18 11:40
Duplicate of #3640

**Closed by rpherbig** 2019-09-18 11:40 UTC
