### ISSUE TITLE
fam keeps getting app'd

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#406] opened 2016-05-27 20:03 UTC
Familiar keeps getting appraised in combat
(bear)

**Comment by xtremenerdrage** [comment] 2016-05-27 20:04
a russet bear

**Comment by rpherbig** [comment] 2016-05-27 20:19
I think this is a duplicate of #57

**Comment by rpherbig** [comment] 2016-06-06 02:22
From @rcuhljr : Add noun list of ignored npc's so combat trainer doesn't count familiars, pets, and other stuff as enemies

**Comment by rcuhljr** [comment] 2016-06-13 04:59
ground work in place, drinfomon should be better at picking out the nouns of stupidly named npcs like yellow and gold banded lizard with sparkly hair.

**Comment by rcuhljr** [comment] 2016-06-14 01:18
Fixed, add npc nouns to ignored_npcs:

```
ignored_npcs:
 - Brokk
 - bear
```

**Closed by rcuhljr** 2016-06-14 01:18 UTC
Labels: combat-trainer
