### ISSUE TITLE
empathic shock with combat-trainer

### ISSUE THREAD

**Issue by blaylosw** [rpherbig/dr-scripts#1851] opened 2017-08-20 04:48 UTC
For some reason  combat-trainer had me attack a prereni as an empath.

```
[combat-trainer]>attack
You leap out of hiding and ambush a young blue-dappled prereni, completely surprising him.
< Moving with incredible power and control, you thrust a steel throwing spike with a tempered blade at a young blue-dappled prereni.  A young blue-dappled prereni attempts to dodge, moving almost completely out of harm's reach.  The spike lands a good hit to the prereni's neck.

Pain blossoms within you, your delicate empathic senses singing with agony.  You feel the wound to the other life essence almost before it happens, your empathy focusing and magnifying the pain you have caused.  You draw back instinctively, your empathy recoiling, leaving you briefly stunned.
[You're bruised, nimbly balanced and in dominating position.]
[Roundtime 2 sec.]
>
Moving strongly, a young blue-dappled prereni kicks out its hooves at a young blue-dappled prereni.  A young blue-dappled prereni fails to evade.  The hoof lands a good hit to his chest!  
>
[combat-trainer]>pre bs 5
You are still stunned.
>
[combat-trainer]>pre bs 5
You are still stunned.
>
[combat-trainer]>pre bs 5
>
You are still stunned.
>
A young blue-dappled prereni wakes up.
>
The blue-dappled prereni breathes slowly, its large ears twitching lightly as it sleeps.
>
Moving well, a young blue-dappled prereni bares its large teeth and bites at a young blue-dappled prereni.  A young blue-dappled prereni attempts to evade.  The bite lands a brushing strike to his left leg!  
>
[combat-trainer]>pre bs 5
You are still stunned.
>
[combat-trainer]>pre bs 5
You are still stunned.
>
[combat-trainer]>pre bs 5
>
With tense movements you prepare your body for the Blood Staunching spell.
```

**Comment by rpherbig** [comment] 2017-08-20 09:45
Can you run this and report the output? `;en echo DRStats.empath?`

**Comment by blaylosw** [comment] 2017-08-20 14:37
--- Lich: exec1 active.
--- Exception: undefined method `empath' for Scripting::DRStats:Class
exec1:1:in `script'
--- Lich: exec1 has exited

**Comment by blaylosw** [comment] 2017-08-20 14:40
sorry it came back as 
-- Lich: exec1 active.
[exec1: true]
--- Lich: exec1 has exited

**Comment by rcuhljr** [comment] 2017-08-20 17:03
Can you link your yamls from an `;e help_me`?

**Comment by blaylosw** [comment] 2017-08-20 17:49
https://pastebin.com/mpKqfUGp

https://pastebin.com/U8bVuN7F

**Comment by rcuhljr** [comment] 2017-08-21 03:22
We could probably just have combat-trainer/hunting-buddy/training-manager refuse to start if guild isn't set. This is most likely caused by a bad autostart or something on drinfomon and it not picking up your class.

**Comment by blaylosw** [comment] 2017-08-21 03:42
I am going to test it more in the next couple days.  Life is in the way right now.  I will let you know

**Comment by MahtraDR** [comment] 2021-12-23 09:04
@rpherbig I reckon we can close this. Looking at the yaml linked, 
```
hunting_info:
- :zone:  young_blue_dappled_prereni
  duration: 60
  args:
  - d0 ## this should be d4
  stop_on:
  - Debilitation
hunting_file_list:
- setup
- back
```

I just helped someone else debug an issue like this, and the problem was that she too, had -d0

Can close.

**Closed** 2021-12-23 22:11 UTC
