### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#381] opened 2016-05-11 02:50 UTC
>;train strength
--- Lich: train active.
[train: to_train: {"strength"=>1}]
[train]>tdp project strength 1
Please specify a goal that is HIGHER than your current attribute.
>
[train: *** ERROR CALCULATING TDP COST FOR 'strength 1'***]
--- Lich: train has exited.

-------------------------------------------

>inf

Name: Summoner Fake Nameeen, Caidis Sanjad of Therengia   Race: Human   Guild: Warrior Mage
Gender: Male   Age: 80   Circle: 93
You were born on the 12th day of the 2nd month of Ka'len the Sea Drake in the year of the Amber Phoenix, 339 years after the victory of Lanival the Redeemer.

Your birthday is more than 2 months away.

You affirmed your vows before the gods in the 8th month of Skullcleaver the Dwarven Axe in the year of the Amber Phoenix, 381.

     Strength :  40              Reflex :  42  
      Agility :  41            Charisma :  32  
   Discipline :  45              Wisdom :  48  
 Intelligence :  50             Stamina :  40  

Concentration : 250    Max : 250

       Favors : 10
         TDPs : 3304
  Encumbrance : None

Wealth:
  No Kronars.
  No Lirums.
  No Dokoras.

Debt:
  You owe 2 silver, 3 bronze, and 4 copper Kronars to the Principality of Zoluren. (234 copper Kronars)
  You owe 8 gold, 8 bronze, and 6 copper Lirums to the Province of Therengia. (8086 copper Lirums)
  You owe 3 gold, 1 silver, 4 bronze, and 4 copper Lirums to the Collection of Qi. (3144 copper Lirums)

**Comment by rpherbig** [comment] 2016-05-11 02:58
I've seen this before, I think it is the same root cause as #343: sometimes `drinfomon` just doesn't pick up the data when it issues the `info` command.

As a workaround, after `train` fails, run `info` manually, then run `train` again.

**Comment by rcuhljr** [comment] 2016-05-11 03:02
I had him do that it didn't work, I think it's his post title.

**Comment by rcuhljr** [comment] 2016-05-11 03:03
Well nevermind, the title should still match

**Comment by rcuhljr** [comment] 2016-05-11 03:08
ah found it, it's his vow line. it throws off the parsing.

**Comment by rpherbig** [comment] 2016-05-11 11:02
Fixed by 9b67f3b35f3a289d37d30ba03c6227def64b62ed?

**Comment by rcuhljr** [comment] 2016-05-11 18:16
Yeah should be fixed.

**Closed by rcuhljr** 2016-05-11 18:16 UTC
