### ISSUE TITLE
Ignoring certain items from base-stealing.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#583] opened 2016-08-06 15:40 UTC
There are some items, such as cauldrons, that are a bit cumbersome to steal. They don't always fit in bags, or fill them up so quickly that you run around doing nothing with hands full. Possibly there needs to be a way to either ignore certain items on the list, or to not bag certain items on the list.

**Comment by rpherbig** [comment] 2016-08-08 02:15
Closing as a duplicate of #582.

**Closed by rpherbig** 2016-08-08 02:15 UTC
