### ISSUE TITLE
Cast failure on GS leaves your empath hanging, no longer actively hunting

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#1741] opened 2017-06-23 02:39 UTC
[combat-trainer]>cast custom
Currently lacking the skill to complete the pattern, your spell fails completely.
>
* As if fumbling muscle flab were natural, a dire bear swipes with powerful and sharp claws at you.  You fend off some of the claw with a steel throwing spike.
[You're adeptly balanced and in strong position.]
>
* As if fumbling muscle flab were natural, a dire bear swipes with powerful and sharp claws at you.  You knock aside some of the claw with a steel throwing spike.
[You're adeptly balanced and overwhelming your opponent.]
>
A dire bear continues to move with a curious lethargy, as if there was some invisible weight on it.
>
Moving strongly, a dire bear swipes with powerful and sharp claws at a dire bear.  A dire bear fails to evade.  The claw lands a hard hit (5/23) to its back!
>
A dire bear swipes with powerful and sharp claws at a dire bear.  A dire bear dodges, barely twisting out of a tight spot.
>
You feel fully rested.
>
* In a weak and directionless display of aggression, a dire bear swipes with powerful and sharp claws at you.  You evade, jumping to one side.
[You're nimbly balanced with no advantage.]
>
* Ineptly, a dire bear slices wide at you.  You fend off some of the claw with a steel throwing spike.
[You're nimbly balanced and in excellent position.]
>
Moving strongly, a dire bear slices wide at a dire bear.  A dire bear fails to dodge.  The claw lands a strong hit (6/23) to its right arm!
>
With skill, a dire bear swipes with powerful and sharp claws at a dire bear.  A dire bear fails to dodge.  The claw lands a hard hit (5/23) that barely punctures the skin on the upper chest causing a slight welt!
>
A dire bear appears less distracted.
>
[hunting-buddy: ***STATUS*** 3 minutes of hunting remaining or waiting on Light Armor, Evasion, Tactics]
A dire bear saunters forward, its jaws wide open in menacing fashion at a dire bear.  A dire bear evades, barely leaning out of harm's reach.
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 20]
[combat-trainer: message: Currently lacking the skill to complete the pattern, your spell fails completely.]
[combat-trainer: message: * As if fumbling muscle flab were natural, a dire bear swipes with powerful and sharp claws at you.  You fend off some of the claw with a steel throwing spike.  ]
[combat-trainer: message: [You're adeptly balanced and in strong position.]]
[combat-trainer: message: * As if fumbling muscle flab were natural, a dire bear swipes with powerful and sharp claws at you.  You knock aside some of the claw with a steel throwing spike.  ]
[combat-trainer: message: [You're adeptly balanced and overwhelming your opponent.]]
[combat-trainer: message: A dire bear continues to move with a curious lethargy, as if there was some invisible weight on it.]
[combat-trainer: message: Moving strongly, a dire bear swipes with powerful and sharp claws at a dire bear.  A dire bear fails to evade.  The claw lands a hard hit to its back!  ]
[combat-trainer: message: A dire bear swipes with powerful and sharp claws at a dire bear.  A dire bear dodges, barely twisting out of a tight spot.  ]
[combat-trainer: message: Manifest Force  (19 roisaen)]
[combat-trainer: message: Vigor  (7 roisaen)]
[combat-trainer: message: Earth Meld  (11 roisaen)]
[combat-trainer: message: Iron Constitution  (5 roisaen)]
[combat-trainer: message: You feel fully rested.]
[combat-trainer: message: * In a weak and directionless display of aggression, a dire bear swipes with powerful and sharp claws at you.  You evade, jumping to one side.  ]
[combat-trainer: message: [You're nimbly balanced with no advantage.]]
[combat-trainer: message: * Ineptly, a dire bear slices wide at you.  You fend off some of the claw with a steel throwing spike.  ]
[combat-trainer: message: [You're nimbly balanced and in excellent position.]]
[combat-trainer: message: Moving strongly, a dire bear slices wide at a dire bear.  A dire bear fails to dodge.  The claw lands a strong hit to its right arm!  ]
[combat-trainer: message: With skill, a dire bear swipes with powerful and sharp claws at a dire bear.  A dire bear fails to dodge.  The claw lands a hard hit that barely punctures the skin on the upper chest causing a slight welt!  ]
[combat-trainer: message: A dire bear appears less distracted.]
[combat-trainer: checked against [/^Your spell backfires/i, /Your spell barely backfires/i, /You strain, but are too mentally fatigued/i, /^You gesture/i, /A soft silver glow envelops/i, /You listen intently to the air/i, /You close (your|yours) eyes/i, /Your target pattern dissipates/i, /You make a .* gesture/i, /You raise your (left|right) hand skyward/i, /Flickering shadows tear away/i, /You sense a Malediction/i, /You release an accompaniment/i, /You roll your hands in an elliptical pattern/i, /You (cup|wave|raise) your hand/i, /You flicker your malevolent desires towards/i, /You clench your hands into fists and grit your teeth/i, /Tendrils of flame dart along your hand/i, /Invisible strands of air twist/i, /The flames dancing along your fingertips/i, /^You can't cast that at yourself/i, /^You need to specify a body part to consume/i, /You breathe deeply, centering your energies/i, /You strike your heel against the ground/i, /You clasp your hands together/i, /With a wave of your hand/i, /Your words fill you with an unflagging sense of resolve and purpose/i, /A renewed sense of purpose fills you/i, /You clench your fist and mutter a whispered/i, /You call forth the dark will of the divine/i, /^Your heart skips a beat/i, /You whisper the final word of your spell/i, /^You rebuke a/i, /You clap (you|your) hands/i, /You are pulled through your unstable Moongate/i, /You thrust your/i, /Your mind races/i, /You draw forth a pulse of/i, /A crackling mantle of blazing orange-yellow flames/i, /You speak a few words of righteousness/i, /You give sudden voice/i, /You hold out your arms/i, /^With a slight flick, you point one of your fingers/i, /^You reach (out|up with|with your|one hand|with both)/i, /You place your hands on your temples/i, /Using your left hand, you channel the spell's energies and gesture/i, /You steeple your fingers together/i, /You successfully weave the .* spell into the receptive aura of the orb/i, /The energy contained in your ritual flutters away impotently as it seeks the open skies/i, /At the ritual's peak, your prophetic connection blooms a thousand-fold/i, /Traces of your prior ritual still linger about you/i, /You swipe your fingertips/i, /^Your spirit lashes out/i, /You open your arms in a hieratic gesture/i, /^A (white|silver) static/i, /^A (glowing amber|crimson) mist/i, /^Disregarding the pain, you grind the dirt brutally into the palm of your hand/i, /^You lift your right hand/i, /You roar and draw your arms back/i]]
>
You can no longer see openings in a dire bear's defenses.
>
* Ineptly, a dire bear swipes with powerful and sharp claws at you.  You dodge, moving out of the way.
[You're nimbly balanced with no advantage.]
>
* As if effort and skill were a bad thing, a dire bear charges with surprising speed at you.  You counter some of the body with a steel throwing spike.
[You're nimbly balanced and in excellent position.]
>
A dire bear swipes with powerful and sharp claws at a dire bear.  A dire bear evades, barely twisting out of harm's reach.
>
A dire bear swipes with powerful and sharp claws at a dire bear.  A dire bear dodges, barely leaning out of harm's reach.
>
A dire bear saunters forward, its jaws wide open in menacing fashion at a dire bear.  A dire bear evades, leaning to one side with no room to spare.
>
* Tentatively, a dire bear swipes with powerful and sharp claws at you.  You evade, twisting to one side.
[You're nimbly balanced with no advantage.]
>
* As if fumbling muscle flab were natural, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You evade, leaning just out of harm's reach.
[You're nimbly balanced and in strong position.]
>
* Apparently without direction or thought, a dire bear swipes with powerful and sharp claws at you.  You evade, managing to get out of the way with a minimum of effort.
[You're nimbly balanced and in strong position.]
>
Moving well, a dire bear swipes with powerful and sharp claws at a dire bear.  A dire bear fails to evade.  The claw lands a good strike (3/23) to its right eye!

**Comment by jayRyan24** [comment] 2017-06-30 19:43
Ah, there's an active issue for this. I've experienced this a lot myself. Since it's not, I guess uncommon, I'll look more into it. Frankly, I think we're maybe using GS before we're ready, but it shouldn't completely stall out.

**Comment by MahtraDR** [comment] 2022-02-09 09:53
Closing. I can't reproduce this.

**Closed by MahtraDR** 2022-02-09 09:53 UTC
Labels: Script: combat-trainer, Guild: Empath
