### ISSUE TITLE
Alchemy not working

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#771] opened 2016-09-10 16:53 UTC
[drscripts]-You: "  anyone else finding alchemy busted?     You get some dried red flowers from inside your backpack.     You realize the red flowers is not required to continue crafting the blister cream, so you stop.      [remedy]>crush my red flowers with my pestle      It would work better if the flowers was in a mortar."
[drscripts]-DR:Etreu: "submit an issue with a log for crannach."
[drscripts]-DR:Sagadin: "I've been having that same issue Barder"

[Barder(24).txt](https://github.com/rpherbig/dr-scripts/files/465514/Barder.24.txt)

**Comment by Sagadin** [comment] 2016-09-10 16:57
I'm having a similar issue with trying to crush red flowers, when there is already ointment in the mortar

**Comment by rpherbig** [comment] 2016-09-10 17:16
Could the the same root cause as #749, but it's hard to tell.

**Comment by jandersson** [comment] 2016-09-10 17:22
I think he meant dartellum

**Comment by Aurayn** [comment] 2016-09-10 18:33
FYI if it helps I did a second run to make sure there was nothing in the mortar

**Comment by Dartellum** [comment] 2016-09-11 00:50
I have ran through workorders again and cannot reproduce this moment. I will continue to test.

**Comment by Sagadin** [comment] 2016-09-14 03:08
Problem with combining water...

[workorders]>get water from my toolbag
You get some water from inside your leather toolbag.
>
[workorders]>count my water
There are three parts left of the water.
>
[workorders]>get water from toolbag
What were you referring to?
>
[workorders]>put my water in my toolbag
You put your water in your leather toolbag.
>
[workorders]>get water from toolbag
You get some water from inside your leather toolbag.
>
[workorders]>combine water
You must be holding both substances to combine them.  For more information, see HELP VERB COMBINE.
>
[workorders: *** No match was found after 15 seconds, dumping info]
[workorders: messages seen length: 1]
[workorders: message: You must be holding both substances to combine them.  For more information, see HELP VERB COMBINE.]
[workorders: checked against [/You combine/i]]
[workorders]>stow right
You put your water in your hiker's rucksack.

**Comment by rpherbig** [comment] 2016-09-21 13:53
Should be fixed in #837

**Closed by rpherbig** 2016-09-21 13:53 UTC
Labels: Crafting
