### ISSUE TITLE
Play.lic not handling cleaning instruments

### ISSUE THREAD

**Issue by RohkDR** [rpherbig/dr-scripts#4661] opened 2020-12-16 13:35 UTC
Is there anyway someone could add this to play.lic? It seems to not handle cleaning of instruments when they dirty, which effects learning potential from what I've seen. Thanks

**Comment by rpherbig** [comment] 2020-12-16 15:17
`play.lic` does not clean, but `performance.lic` does. Can you give the other script a try?

**Comment by vtcifer** [comment] 2020-12-16 15:20
AFAIK, this is intended for play.lic.  You should be regularly running performance to update your song anyways, and play.lic is designed to be just super minimal and 0 interference with other scripts.  Adding in a clean routine would break that concept.

**Comment by RohkDR** [comment] 2020-12-16 16:01
Yea I know performance does all that rpherbig. And suppose I never looked at the play script, your right.. it is minimal. You can delete this if you can, or i can close it.

**Comment by jandersson** [comment] 2021-01-09 00:51
Play shouldn't clean instruments. Its by design as folks mention a simple script with no interaction besides playing the instrument. Cleaning an instrument takes roundtime, so you have to know when and where to do it. The amount of work that takes is simply not worth it - and as far as I could tell; dirty zills teaches the same as clean ones or close enough.

**Comment by jandersson** [comment] 2021-01-09 00:57
Forgot to mention: cleaning also requires moving and removing gear which is complicated. It might be possible with perfect harmony between  scripts, but as it stands theyre isolated :(

**Comment by MahtraDR** [comment] 2021-12-11 07:05
Can we close this? It's widely agreed play is very basic and does what it does. Cleaning, and song choosing for skill come from performance, that's the documented, intended behaviour.

**Comment by asechrest** [comment] 2021-12-27 06:32
@rpherbig Ok to close this per prior comments. Working as intended. Thanks.

**Closed** 2021-12-27 20:23 UTC
