### ISSUE TITLE
;buff set names should be case insensitive

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1841] opened 2017-08-11 06:24 UTC
You cannot use a skill name or any part of the skill name in a waggle set.
```
  Warding:
    Manifest Force:
      abbrev: maf
      recast: 99999
      mana: 5
      cambrinth:
      - 5
      - 5
      - 5
      - 4

> ,buff Warding

--- Lich: buff active.

--- Lich: buff has exited.

> ,buff 1Warding

--- Lich: buff active.

--- Lich: buff has exited.

> 
```

**Comment by rpherbig** [comment] 2017-08-11 18:42
I think the issue is actually capitalization. Try naming it `warding` (all lower case).

**Comment by intangibles** [comment] 2017-08-11 19:23
Great, that worked.

I had tried that (and like 50 other variations) but something else must have been blocking it when i was trying lower case.  

Thank you!

**Comment by rpherbig** [comment] 2017-08-20 16:50
Overcome by #1850

**Comment by MahtraDR** [comment] 2022-01-05 07:42
@rpherbig Close this one too?

**Closed** 2022-01-05 18:18 UTC
