### ISSUE TITLE
Combat-trainer and swapping weapons while wounded.

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3741] opened 2019-08-10 20:24 UTC
It puts me in an endless loop and I just stand there taking hits over and over again.

[combat-trainer]>swap my riste

!> 
Your left hand is too injured to do that.
!> 
* Tentatively, a silver-backed bear swipes with powerful and sharp claws at you.  You dodge, stepping aside with ease.  
[You're hurt, nimbly balanced and have slight advantage.]
!> 
* Moving well, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, barely twisting out of harm's reach.  
[You're hurt, nimbly balanced with opponent in better position.]
!> 
* A dire bear swipes with powerful and sharp claws at you.  You counter little of the claw with a darkstone half-handled riste.  
[You're hurt, nimbly balanced with opponent in good position.]
!> 
* Tentatively, a silver-backed bear swipes with powerful and sharp claws at you.  You turn aside most of the claw with a darkstone half-handled riste.  
[You're hurt, nimbly balanced and in very strong position.]
!> 
A shower of blazing fire continues to fall from the sky to the northwest!
!> 
* As if fumbling muscle flab were natural, a silver-backed bear swipes with powerful and sharp claws at you.  You knock aside some of the claw with a darkstone half-handled riste.  
[You're hurt, solidly balanced and opponent has slight advantage.]
!> 
* Awkwardly, a silver-backed bear slices wide at you.  You counter most of the claw with a darkstone half-handled riste.  
[You're hurt, solidly balanced and in very strong position.]
!> 
* A dire bear swipes with powerful and sharp claws at you.  You evade, barely managing to get out of the way.  
[You're hurt, nimbly balanced and have slight advantage.]
!> 
* Trying weakly, a dire bear swipes with powerful and sharp claws at you.  You turn aside little of the claw with a darkstone half-handled riste.  
[You're hurt, nimbly balanced with opponent in good position.]
!> 
* As if effort and skill were a bad thing, a silver-backed bear swipes with powerful and sharp claws at you.  You dodge, moving cleanly out of the way.  
[You're hurt, nimbly balanced and in good position.]
!> 
[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 27]

[combat-trainer: message: [You're hurt, nimbly balanced and in good position.]]

[combat-trainer: message: * As if effort and skill were a bad thing, a silver-backed bear swipes with powerful and sharp claws at you.  You dodge, moving cleanly out of the way.  ]

[combat-trainer: message: [You're hurt, nimbly balanced with opponent in good position.]]

[combat-trainer: message: * Trying weakly, a dire bear swipes with powerful and sharp claws at you.  You turn aside little of the claw with a darkstone half-handled riste.  ]

[combat-trainer: message: [You're hurt, nimbly balanced and have slight advantage.]]

[combat-trainer: message: * A dire bear swipes with powerful and sharp claws at you.  You evade, barely managing to get out of the way.  ]

[combat-trainer: message: [You're hurt, solidly balanced and in very strong position.]]

[combat-trainer: message: * Awkwardly, a silver-backed bear slices wide at you.  You counter most of the claw with a darkstone half-handled riste.  ]

[combat-trainer: message: [You're hurt, solidly balanced and opponent has slight advantage.]]

[combat-trainer: message: * As if fumbling muscle flab were natural, a silver-backed bear swipes with powerful and sharp claws at you.  You knock aside some of the claw with a darkstone half-handled riste.  ]

[combat-trainer: message: A shower of blazing fire continues to fall from the sky to the northwest!]

[combat-trainer: message: Sanctify Pattern  (Fading)]

[combat-trainer: message: Minor Physical Protection  (14 roisaen)]

[combat-trainer: message: Centering  (12 roisaen)]

[combat-trainer: message: Benediction  (12 roisaen)]

[combat-trainer: message: Osrel Meraud  (100%)]

[combat-trainer: message: Bless  (9 roisaen)]

[combat-trainer: message: Major Physical Protection  (6 roisaen)]

[combat-trainer: message: [You're hurt, nimbly balanced and in very strong position.]]

[combat-trainer: message: * Tentatively, a silver-backed bear swipes with powerful and sharp claws at you.  You turn aside most of the claw with a darkstone half-handled riste.  ]

[combat-trainer: message: [You're hurt, nimbly balanced with opponent in good position.]]

[combat-trainer: message: * A dire bear swipes with powerful and sharp claws at you.  You counter little of the claw with a darkstone half-handled riste.  ]

[combat-trainer: message: [You're hurt, nimbly balanced with opponent in better position.]]

[combat-trainer: message: * Moving well, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, barely twisting out of harm's reach.  ]

[combat-trainer: message: [You're hurt, nimbly balanced and have slight advantage.]]

[combat-trainer: message: * Tentatively, a silver-backed bear swipes with powerful and sharp claws at you.  You dodge, stepping aside with ease.  ]

[combat-trainer: message: Your left hand is too injured to do that.]

[combat-trainer: checked against [/ (light edged|medium edged) /i, /\briste\b.*(heavy edged|two-handed edged|heavy blunt|two-handed blunt|light edged|medium edged|light blunt|medium blunt|light thrown|short staff|quarter staff|halberd)/i]]

[combat-trainer: for command swap my riste]

[combat-trainer]>swap my riste

Your left hand is too injured to do that.

**Comment by Kaesken** [comment] 2019-09-06 17:19
Here's another one:

[combat-trainer]>swap my riste

* Looking as if this were a bad idea, an Endrus serpent bites at you.  You partially block with a metal target shield.  
[You're solidly balanced and opponent has slight advantage.]
> 
Will alone cannot conquer the paralysis that has wracked your body.
> 
[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 21]
> ,ka

**Comment by rpherbig** [comment] 2019-09-18 11:39
Duplicate of #3640

**Closed by rpherbig** 2019-09-18 11:39 UTC
