### ISSUE TITLE
Theurgy does not stop playing instrument

### ISSUE THREAD

**Issue by GahstonDR** [rpherbig/dr-scripts#4487] opened 2020-09-13 15:11 UTC
Theurgy.lic does not stop playing instrument when cleaning altars with holy water causing the script to get stuck indefinately.

[Temple of Light, Gela Arenen]
The first sight on entering the room is the eastern wall, covered with a vast painting of the lands stretching to the east of Shard.  The rosy fingers of dawn reach toward the ceiling, across which the colors darken to a deep, velvety purple above the dim mountains on the western horizon.  You also see a carved wooden altar.
Also here: Master Healer Dreadkhurault.
Obvious exits: west.
Room Number: 8178
>
[go2: travel time: 0:00:03]
--- Lich: go2 has exited.
[play]>play serenade
You begin a quiet serenade on your thin-edged zills with only the slightest hint of difficulty.
>
[theurgy]>get chalice from my watersilk bag
You get a carved bone chalice inset with copper bands from inside your watersilk bag.
>
[theurgy]>clean altar with holy water
You are a bit too busy performing to do that.
>
You feel fully prepared to seek assistance from the Immortals once again.
>
You continue playing on your thin-edged zills.
>
You continue to play a quiet serenade on your thin-edged zills, stumbling only a little through a difficult section.
>
Your body below the waist is still soaked.
>
You continue playing on your thin-edged zills.

**Comment by rpherbig** [comment] 2020-09-13 17:59
It looks like the problem is that `play` uses `sanowret_no_use_scripts` to determine when it should and should not play. `theurgy` is not in that list.

Here's my question, and I hope @GahstonDR you can help me out here. Can you use your sanowret scrystal during `theurgy`?

**Comment by GahstonDR** [comment] 2020-09-13 19:09
> It looks like the problem is that `play` uses `sanowret_no_use_scripts` to determine when it should and should not play. `theurgy` is not in that list.
> 
> Here's my question, and I hope @GahstonDR you can help me out here. Can you use your sanowret scrystal during `theurgy`?

I have sanowret running all the time as an autostart and never ran into an issue with it so i always assumed it was ok

**Comment by jayRyan24** [comment] 2020-09-15 14:22
I pushed a fix, please test.

**Comment by GahstonDR** [comment] 2020-09-18 18:12
ill test it out today! thanks everyone

**Closed** 2020-09-19 00:19 UTC
Labels: Script: play, Script: theurgy
