### ISSUE TITLE
Fix oxford commas issues

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#12] opened 2015-11-19 15:52 UTC

**Comment by rpherbig** [comment] 2015-11-19 17:40
@rcuhljr Can you elaborate on what issues you were seeing?

**Comment by rcuhljr** [comment] 2015-11-19 21:58
I think I've fixed it? the list_to_thing methods where returning empty items "" since it would double split on `and,`. I haven't run into it in awhile.

**Comment by rcuhljr** [comment] 2015-11-27 01:13
Closing until someone can reproduce an actual problem.

**Closed by rcuhljr** 2015-11-27 01:13 UTC
Labels: common
