### ISSUE TITLE
;buff doesn't honor buff_spell_mana_threshold

### ISSUE THREAD

**Issue by mithgrek** [rpherbig/dr-scripts#2352] opened 2018-01-10 23:21 UTC
The setting buff_spell_mana_threshold  is not used by buff.  I know combat-trainer does, but buff does not.

buff calls cast_spell from common-arcana, which checks only that mana > 40.  This happens to match the default buff_mana_threshold in base-yaml, but it's hard-coded.

From common-arcana:

 def cast_spells(spells, settings, force_cambrinth = false)
    infuse_om(!settings.osrel_no_harness, settings.osrel_amount)
    spells.each do |name, data|
      next if DRSpells.active_spells[name] && (data['recast'].nil? || DRSpells.active_spells[name].to_i > data['recast'])
      while mana < 40
        echo('Waiting on mana...')
        pause 15
      end

      cast_spell(data, settings, force_cambrinth)
    end
  end

This function seems to be used only in buff style by other scripts, so changing the "while mana < 40" to checking the buff threshold should match the intent.

shield@gemstone:~/lich/scripts$ grep cast_spells *.lic
astrology.lic:    cast_spells(buffs, settings)
attunement.lic:    cast_spells(settings.waggle_sets['attunement'], settings)
buff.lic:      cast_spells(spells, settings, settings.waggle_force_cambrinth)
common-arcana.lic:  def cast_spells(spells, settings, force_cambrinth = false)

If it could be used by other scripts for offensive/targeted/whatever spells, then perhaps a different function, or an optional parameter to cast_spells to pass the minimum mana required.

For an advanced, less-trivial option... make cast_spells smart enough to only cast a spell if it has the attunement (and/or charged cambrinth) to succeed.

**Comment by MahtraDR** [comment] 2022-02-08 00:24
Closing as this issue was resolved between then and now sometime. Can't reproduce today.

**Closed by MahtraDR** 2022-02-08 00:24 UTC
