### ISSUE TITLE
Add support for lockbox picking in combat

### ISSUE THREAD

**Issue by DRWafflesworth** [rpherbig/dr-scripts#3733] opened 2019-08-03 00:11 UTC
Since locksmith trainers are becoming more common, could we add support for them in combat with retreating being optional?

**Comment by Dartellum** [comment] 2019-09-06 17:20
Already support this:
training_abilities:
  Locks: 200

**Comment by jandersson** [comment] 2020-05-30 03:30
wrt retreating, is it possible to pick a box at melee? Why should it be optional if not?

**Comment by Dartellum** [comment] 2020-05-30 09:01
Cannot pick at melee. Message is too busy to do that.

**Comment by MahtraDR** [comment] 2022-02-10 03:16
Closing as a duplicate of https://github.com/rpherbig/dr-scripts/issues/3733 purely because that one has a lot more info/context, so makes more sense to me that we keep that one.

**Closed by MahtraDR** 2022-02-10 03:16 UTC
Labels: Script: combat-trainer
