### ISSUE TITLE
Request to potentially change crafting belts to be craft specific instead of skill specific

### ISSUE THREAD

**Issue by HaxenDR** [rpherbig/dr-scripts#1692] opened 2017-06-07 13:27 UTC
I have a crafting belt for shaping and one for tinkering, but the YAML only has a flag for "Engineering_belt:".
Currently I have one belt commented out, but it would be nice to be able to say "Shaping_Belt" and "Tinkering Belt"  in the YAML for the crafting scripts without having to edit the YAML. I tried putting 2 belts in since it's a list format, but it broke the list and the scripts just ignored the belts all together trying to "get" everything instead of "untie".

**Comment by MahtraDR** [comment] 2023-01-24 11:36
Closing as dupe of https://github.com/rpherbig/dr-scripts/issues/1420

**Closed by MahtraDR** 2023-01-24 11:36 UTC
Labels: Crafting, Script: shape, Script: tinker
