### ISSUE TITLE
Dual load support for barbarians

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#681] opened 2016-08-28 20:37 UTC
http://pastebin.com/9Mbk3M8s

**Comment by rpherbig** [comment] 2016-08-28 20:54
Sadly, Flame is not a prerequisite for Eagle, so we can't always tell if Eagle is active. Do we want to "if Barbarian then try to dual load" and handle the failure?

**Comment by rpherbig** [comment] 2016-10-07 17:02
Duplicate of #852

**Closed by rpherbig** 2016-10-07 17:02 UTC
Labels: combat-trainer
