### ISSUE TITLE
safe-room messaging error

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1943] opened 2017-09-23 18:03 UTC
--- Lich: safe-room active.

[safe-room]>health

Your body feels very beat up.
Your spirit feels full of life.
You have some minor abrasions to the right arm, minor swelling and bruising around the left arm compounded by cuts and bruises about the left arm, minor swelling and bruising around the left leg compounded by cuts and bruises about the left leg, some minor abrasions to the right hand, minor swelling and bruising in the chest area compounded by cuts and bruises about the chest area, some minor abrasions to the left eye.
You have a seriously poisoned right hand.
You have a dangerously poisoned chest.

> 
[safe-room: ***STATUS*** No wounds, skipping healing]

--- Lich: safe-room has exited.

**Comment by jandersson** [comment] 2017-09-25 20:21
Duplicate of #1584

**Closed** 2017-09-25 20:28 UTC
