### ISSUE TITLE
Crossing-Repair running while other scripts running - causing issues

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#2642] opened 2018-04-25 21:59 UTC
I have a complete log I would be happy to share, but it's really long.  I've broken down what I think is pertinent to the issue.  I have made no changes to my yaml except adding the :skip_repair: true setting, but I have been having problems on and off with this for a couple of weeks.

Crossing-repair just seems to start up on its own...with other scripts starting up as well, causing the entire training process to stop.  Please see edited log below.

Gabellia

*******************************************************

***Crossing repair successfully repaired all my items.

--- Lich: crossing-repair has exited.

--- Lich: sell-loot active.

[sell-loot]>open my haversack

***Sell-loot does its thing

--- Lich: buff active.

***Took me to safe room where it prepped and invoked my town-training spell (GHS) but then......

[hunting-buddy]>inv combat

You aren't harnessing any mana.
All of your combat:

  a cerulean sprite-bone parry stick tangled in withered vines
  some notched wood drake-bone sleeves
  a damite ring cap
  a damite ring mask
  some damite ring greaves
  a damite ring mantle
  a damite ring tasset
  a damite targe
  some spiked knuckles
  some knee spikes
  some blued steel elbow spikes shaped like sharp vulpine fangs
  some steel-toed footwraps
[Type INVENTORY HELP for more options]

[hunting-buddy]>sort auto head

Your inventory is now arranged in head-to-toe order.

--- Lich: hunting-buddy has exited.

[safe-room: ***STATUS*** No wounds, skipping healing]

--- Lich: safe-room has exited.

--- Lich: crossing-repair active.  <-----Crossing repair started up again

***Takes me to the bank, where it withdraws coin for repair and also tries to cast the spell it prepped in safe room.

You gesture.
Something in the area prevents your spell from working.

--- Lich: buff has exited.

****I then ran around a bunch of rooms...and then back to bank and get this message:

[crossing-repair: Failed to navigate to room 1544, attempting again]

***I now run out of the bank...and attempt to train forging (crossing-repair is still active)

[crossing-training]>withdraw 5 silver

You run out.
[First Provincial Bank, Lobby]
Marble tiled floors covered with heavy rugs and walls of polished jasper that gleam a cool blue mark this bank as solid and secure (and expensive).  An official money-changing booth is to one side and a row of tellers windows faces you.  Several guards, armed and armored, stand ready for trouble of any sort.  Near the tellers stands a table of fine wood for those who need to do some writing.  You also see a money-changer's booth, a bucket of viscous gloop and the tellers' windows.
Also here: Magdelyn.
Obvious exits: out.

Room Number: 1901

You must be at a bank teller's window to withdraw money.

[crossing-training: ***Attempting to train Forging***]

***Go2 is running around...I think trying for repair...but since the forging script is running, I get the "go building" message.

***Go2 exits...but I'm still randomly running around

--- Lich: go2 has exited.

You can't go there.

[go2]>west

You can't go there.
You can't go there.
You run east.
[Grassland Road, Meadow]
A covered merchant's wagon trundles eastward, toward the high walls of the Crossing which are barely visible above their surrounding treetops.  The Gor'Tog merchant gives you a polite nod as he urges his horses on at an eager pace.  Meadows stretch out from either side of the path as far as the eye can see.  
Obvious paths: east, west.

Room Number: 1434

You can't go there.

[go2]>west

What were you referring to?
You can't go there.
You can't go there.
You run west.
[Grassland Road, Meadow]
The road makes a slight bend through the grassy meadows brightened with sunny yellow creeping buttercup and milkweed pods bursting with snowy white fluff.  
Obvious paths: east, south, northwest.

Room Number: 1435

***It's taking me to Randals for repair where I finally arrive.

--- Lich: go2 has exited.

[workorders: Failed to navigate to room 8771, attempting again]

***It moves me OUT of Randals...but since crossing repair is running, I get this:

[crossing-repair]>remove my parry.stick

You loosen the straps securing your parry stick and remove it.

[crossing-repair]>give my parry.stick to Randal

[go2]>out

[go2]>n

[go2]>north

[go2]>east

[go2]>north

[go2]>east

What is it you're trying to give?
You run out.

***Go2 now takes me to Forging society in Crossings where it confirms that crossing-repair and workorders are both running at the same time.

[workorders]>ask Yalda for challenging blacksmithing work

[crossing-repair: *** No match was found after 15 seconds, dumping info]

[crossing-repair: messages seen length: 278]

[crossing-repair: message: Obvious exits: north, east, south, west.]

[crossing-repair: message: Also here: Quicklozmas.]

[crossing-repair: message: Waves of heat, blasting with an almost tangible force, roll from the flames of a brick-lined firepit.  Over the firepit, a blackened granite crucible hangs by stout chains from an oak beam high overhead.  Near the crucible's spout stand stone molds of different shapes, with a pile of fuel within easy reach.  Similar crucibles hang to the north and south.  You also see Forging Society Mistress Yalda, a walnut miniature soldier, an ingot cutter, a large waste bucket and a pile of fuel.]

[crossing-repair: message: [Forging Society, Foundry]]

[crossing-repair: message: You wander west.]

***I wander around the building for a while...then crossing-repair takes me out and back to Randals.  Wandered around for a couple hours then, even *I* don't want to look at the log!!

**Comment by BastionWT** [comment] 2018-04-29 11:49
Restock & Pick started at the same time for me. Issues start at the bottom, included before for completion sake. I bolded the part of the stealth.yaml where the failure is occurring.
https://pastebin.com/LJnET4iF

YAML hunting info included, in order:
hunting_info:
- :zone: orc_raiders_upstairs
  :duration: 15
  args:
    - d0
    - stealth
  before:
  - go2 6163
  **- buff pick
  - pick pets 10
  - pick**
  - go2 6163
  - athletics
  - go2 6163
  - steal
#  - buff athletics
#  - athletics
#  - go2 9081
#  - buff pick
#  - pick
#  - releasekhri
#  - steal
  after:
  - stopforms
  stop_on:
  - Stealth

hunting_info:
- :zone: warklin #germishdin #cave_trolls #gryphons1 #orc_bandits #young_ogres
  :duration: 60
  args:
    - d1
  before:
#  - go2 6164
#  - buff athletics
#  - athletics
#  - go2 9081
#  - buff pick
#  - pick
#  - releasekhri
#  - steal
  after:
  - go2 6163
  - buff pick
  - pick pets 10
  - pick
  stop_on:
  - Small Blunt
  - Crossbow
  - Twohanded Edged
  - Heavy Thrown 
  - Large Blunt
  - Twohanded Blunt
  - Polearms

hunting_info:
- :zone: cave_trolls
  :duration: 25
  args:
    - d0
    - box
  boxes: true
  before:
  - go2 6163
  - athletics
  after:
  - go2 6163
  - pick pets 10
  - pick

**Comment by jandersson** [comment] 2018-04-29 11:57
Can you insert three backtics above and below your yaml code? That will format it

**Comment by BastionWT** [comment] 2018-04-30 01:44
Updated the formatting. Also came home to this:

**Comment by Tarhish** [comment] 2018-09-25 14:41
I got a little more info after talking to Brashton who was having the same problem.  The ones fighting seemed to be workorders trying to repair tools, sell-loot trying to get to the bank, and crossing-repair.

Two logs:
https://pastebin.com/SjLeXs9i
https://pastebin.com/rMWwfjqk
and his yaml: https://pastebin.com/A4pSz35L

**Comment by Tarhish** [comment] 2018-09-30 16:15
I just had it happen to me too - according to Brashton it happened after inserting lumber_while_training.  I turned that on and finally saw it.  I paused all the scripts during a forestry-buddy run for a moment, unpaused them, and then when forestry-buddy was done several minutes later I got this

```
--- Lich: forestry-buddy has exited.
--- Lich: crossing-training active.
[crossing-training]>open my rucksack
...wait 8 seconds.
>
--- Lich: hunting-buddy active.
>
[hunting-buddy]>tap my bundle
[neccrossing-training]>open my rucksack
I could not find what you were referring to.
>
[hunting-buddy]>tap my bundling rope
[crossing-training]>open my haversack
That is already open.
>
You tap a braided bundling rope inside your leather haversack.
>
```

Going to look further into this, but I wanted to write this down first.

**Comment by MahtraDR** [comment] 2023-01-24 10:33
Closing, as it's ancient, and I cannot reproduce today.

**Closed by MahtraDR** 2023-01-24 10:33 UTC
Labels: Script: crossing-repair
